train_file: ['data/vqa_train.json',
             'data/vqa_val.json',   
             'data/vg_qa.json']
             
test_file: ['data/vqa_test.json']
answer_list: 'data/answer_list.json'

vqa_root: '/export/share/datasets/vision/VQA/Images/mscoco/' #train2014/
vg_root: '/export/share/datasets/vision/visual-genome/'  #image/

image_res: 384
batch_size_train: 8
batch_size_test: 8
k_test: 128

alpha: 0.4
distill: False
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 3e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 3e-4, epochs: 1, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







